# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.75

## Mod Properties
mod_id=better_mine_team
mod_name=Better Mine Team
mod_license=MIT
mod_version=2612-0.0.1-PreAlpha1
mod_group_id=com.i113w
mod_authors=i113w, XiaoHuNao
mod_description=Better Mine Team: A tactical team mod with monster taming and dragon riding.

i113w_camera_lib_project_id=1487243
i113w_camera_lib_file_id=8243124
